### ISSUE TITLE
Redesign blinds settings

### ISSUE THREAD

**Issue by adamb56789** [SDP-group22/Helio-app#70]
It should be redesigned to be similar to the other pages.

- [x] The icon selection also needs to be implemented properly, you should be able to select an icon by clicking on the icon in a dropdown menu, and this should then be displayed in the blinds recycler views. I think you should try using a drop down text field like the one used for themes 
- [x] The open and close buttons should be removed since the move requests have been removed from the hub, and this is supposed to be a settings page more than anything.
- [x] We should also consider removing the page with the list of blinds entirely, and accessing the individual settings directly from the control page.
- [x] Also make sure the IP address does
```Java
Patterns.IP_ADDRESS.matcher(url).matches();
```
and update the sensors settings to do the same check as well.
- [x] The only things on the page should be IP, name, icon, motor calibration
- [x] It should use material design text fields and buttons, base it off of the other fragments that do the same
- [x] The new page should be fully connected to the backend of the app

**Comment by Jeremy-hao** [comment]
I agree with removing the whole "Edit blinds" page. We can combine "Control page" and the "Edit blinds" page together. Also, I think we should discuss which kinds of functionalities should be included in the "single blinds setting" page. 

For example, I think it's confusing if we can change the sensor settings on the blind page. What about removing "Motion sensor setting and Light sensor setting"? Because in the sensor page, the sensor can control multiple blinds at the same time. If one of the blinds wants to change its sensor state, it should be accessible from the sensors page instead of blinds page.
